#!/bin/sh
# Make the secrets this deployment needs, once.
#
#   ./secrets.sh > .env
#
# Then fill in the two domains and the address to send certificate notices to.
# Everything above them is generated here and is not recoverable: SAG_ENCRYPTION_KEYS
# is the key every stored credential is sealed with, so losing this file means
# losing every vendor key, every machine's key, and the authority every machine
# chains to. Keep it the way you keep a private key.
#
# Refuses to overwrite by design: it writes to stdout, so `> .env` on a file that
# already exists is your decision and not a script's.
set -eu

if [ -t 1 ]; then
	echo "This writes an environment file to standard output." >&2
	echo "Run:  ./secrets.sh > .env" >&2
	exit 2
fi

hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
# Passwords go in a DSN and a URL, so they are hex too: nothing to quote and
# nothing to escape, at the cost of nothing anybody types by hand.
password() { hex 24; }

cat <<ENV
# Flexie SAG deployment. Generated by ./secrets.sh -- keep this file.
#
# SAG_ENCRYPTION_KEYS is the one that cannot be regenerated: it is the key every
# stored credential is sealed with. Lose it and every vendor key, every machine
# key and the authority every machine chains to become unreadable, with no way
# back. Back it up somewhere that is not this server.

# What this deployment calls itself. Swarm takes the stack name from the command
# line; compose takes it from here, so both name their volumes the same.
COMPOSE_PROJECT_NAME=flexie-sag

# --- who you are ------------------------------------------------------------
# Both must already resolve to this box, or the first start cannot get a
# certificate for them.
SAG_CONSOLE_DOMAIN=admin.example.com
SAG_CHAT_DOMAIN=chat.example.com
# Where a certificate authority sends expiry notices.
SAG_TLS_EMAIL=you@example.com

# --- secrets ----------------------------------------------------------------
SAG_SESSION_SECRET=$(hex 32)
SAG_ENCRYPTION_KEYS=1:$(hex 32)
SAG_ENCRYPTION_PRIMARY_KEY_ID=1
SAG_DB_PASSWORD=$(password)
SAG_DB_ROOT_PASSWORD=$(password)

# --- the machine that runs our own models (optional) ------------------------
# Filled in when a NEW machine is added, not before: a token lasts an hour and
# is spent by the machine that registers on it, so mint it and deploy in one go.
#   docker compose exec orchestrator sag join-token
# The accelerator is a build choice: cuda, metal, mkl, accelerate, or empty for
# the processor. Building for one the box does not have will not start.
SAG_JOIN_TOKEN=
SAG_NODE_ACCEL=
SAG_NODE_NAME=machine-1
ENV
