CREATE TABLE `agent_sessions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `agent_id` bigint(20) unsigned DEFAULT NULL,
  `workflow_version_id` bigint(20) unsigned DEFAULT NULL,
  `parent_session_id` bigint(20) unsigned DEFAULT NULL,
  `channel` varchar(32) NOT NULL,
  `external_key` varchar(64) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `status` enum('running','waiting_user','waiting_approval','scheduled','completed','failed','cancelled') NOT NULL,
  `approval_mode` enum('manual','auto') NOT NULL DEFAULT 'manual',
  `started_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `is_pinned` tinyint(1) NOT NULL DEFAULT 0,
  `last_message_at` datetime(3) DEFAULT NULL,
  `message_count` int(11) NOT NULL DEFAULT 0,
  `next_seq` int(11) NOT NULL DEFAULT 0,
  `uid` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_uid` (`uid`),
  KEY `idx_ws_status` (`workspace_id`,`status`),
  KEY `idx_ws_user` (`workspace_id`,`user_id`),
  KEY `idx_parent` (`parent_session_id`),
  KEY `idx_external` (`workspace_id`,`external_key`),
  KEY `idx_chat_list` (`workspace_id`,`user_id`,`is_pinned`,`last_message_at`),
  KEY `fk_session_user` (`user_id`),
  KEY `fk_session_agent` (`agent_id`),
  KEY `fk_session_version` (`workflow_version_id`),
  FULLTEXT KEY `ft_title` (`title`),
  CONSTRAINT `fk_session_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_session_parent` FOREIGN KEY (`parent_session_id`) REFERENCES `agent_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_session_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_session_version` FOREIGN KEY (`workflow_version_id`) REFERENCES `workflow_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_session_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
