CREATE TABLE `agent_delegations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `session_id` bigint(20) unsigned NOT NULL,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `parent_tool_call_id` varchar(64) NOT NULL,
  `agent_key` varchar(64) NOT NULL,
  `mode` varchar(16) NOT NULL,
  `fleet_id` bigint(20) unsigned DEFAULT NULL,
  `task` text DEFAULT NULL,
  `status` enum('running','done','failed','cancelled') NOT NULL DEFAULT 'running',
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `progress` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`progress`)),
  `result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result`)),
  `error_text` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_session` (`session_id`),
  KEY `idx_session_status` (`session_id`,`status`),
  KEY `fk_delegation_workspace` (`workspace_id`),
  KEY `idx_fleet` (`fleet_id`,`status`),
  CONSTRAINT `fk_delegation_session` FOREIGN KEY (`session_id`) REFERENCES `agent_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_delegation_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_delegation_fleet` FOREIGN KEY (`fleet_id`) REFERENCES `agent_fleets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
