CREATE TABLE `agents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `agent_key` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `instructions` mediumtext DEFAULT NULL,
  `model_id` bigint(20) unsigned DEFAULT NULL,
  `memory_brain_id` bigint(20) unsigned DEFAULT NULL,
  `audio_model_id` bigint(20) unsigned DEFAULT NULL,
  `reasoning` tinyint(1) NOT NULL DEFAULT 0,
  `approval_ttl_seconds` int(10) unsigned DEFAULT NULL,
  `max_iterations` int(10) unsigned DEFAULT NULL,
  `max_fleet_agents` smallint(5) unsigned DEFAULT NULL,
  `background_timeout_seconds` int(10) unsigned DEFAULT NULL,
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `delegation_mode` enum('auto','background','inline','fleet') NOT NULL DEFAULT 'auto',
  `created_at` datetime(3) NOT NULL,
  `settings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`settings`)),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ws_key` (`workspace_id`,`agent_key`),
  KEY `fk_agent_model` (`model_id`),
  KEY `fk_agent_memory_brain` (`memory_brain_id`),
  KEY `fk_agent_audio_model` (`audio_model_id`),
  CONSTRAINT `fk_agent_model` FOREIGN KEY (`model_id`) REFERENCES `ai_models` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agent_memory_brain` FOREIGN KEY (`memory_brain_id`) REFERENCES `brains` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agent_audio_model` FOREIGN KEY (`audio_model_id`) REFERENCES `ai_models` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agent_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
