CREATE TABLE `agent_tool_calls` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `step_id` bigint(20) unsigned NOT NULL,
  `session_id` bigint(20) unsigned NOT NULL,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `tool_call_id` varchar(64) NOT NULL,
  `tool_name` varchar(64) NOT NULL,
  `friendly_name` varchar(255) DEFAULT NULL,
  `args` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`args`)),
  `result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result`)),
  `status` enum('approval_required','running','completed','failed','rejected') NOT NULL,
  `error_text` text DEFAULT NULL,
  `duration_ms` int(11) DEFAULT NULL,
  `execution_order` int(11) NOT NULL DEFAULT 0,
  `requested_approval` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_session_call` (`session_id`,`tool_call_id`),
  KEY `idx_step` (`step_id`),
  KEY `idx_ws_status` (`workspace_id`,`status`),
  CONSTRAINT `fk_call_session` FOREIGN KEY (`session_id`) REFERENCES `agent_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_call_step` FOREIGN KEY (`step_id`) REFERENCES `agent_steps` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_call_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
