CREATE TABLE `agent_park_snapshots` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `token_hash` char(64) NOT NULL,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `session_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `agent_id` bigint(20) unsigned DEFAULT NULL,
  `model_id` bigint(20) unsigned NOT NULL,
  `tool_name` varchar(191) NOT NULL,
  `tool_call_id` varchar(64) NOT NULL,
  `tool_args` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`tool_args`)),
  `action_hash` char(64) NOT NULL,
  `definition_hash` char(64) DEFAULT NULL,
  `agent_key` varchar(64) DEFAULT NULL,
  `parent_tool_call_id` varchar(64) DEFAULT NULL,
  `delegation_id` bigint(20) unsigned DEFAULT NULL,
  `handoff_mode` varchar(16) DEFAULT NULL,
  `status` enum('queued','pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `resolved_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_hash` (`token_hash`),
  KEY `idx_session` (`session_id`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_ws_status` (`workspace_id`,`status`),
  KEY `fk_park_user` (`user_id`),
  KEY `fk_park_delegation` (`delegation_id`),
  CONSTRAINT `fk_park_delegation` FOREIGN KEY (`delegation_id`) REFERENCES `agent_delegations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_park_session` FOREIGN KEY (`session_id`) REFERENCES `agent_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_park_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_park_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
