CREATE TABLE `ai_skills` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `name` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(1024) NOT NULL DEFAULT '',
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_by_name` varchar(255) NOT NULL DEFAULT '',
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `updated_by_name` varchar(255) NOT NULL DEFAULT '',
  `active_version_id` bigint(20) unsigned DEFAULT NULL,
  `status` enum('draft','active','disabled','archived') NOT NULL DEFAULT 'draft',
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ws_skill` (`workspace_id`,`name`),
  KEY `fk_skill_active_version` (`active_version_id`),
  KEY `fk_skill_created_by` (`created_by`),
  KEY `fk_skill_updated_by` (`updated_by`),
  FULLTEXT KEY `ft_skill` (`name`,`title`,`description`),
  CONSTRAINT `fk_skill_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_skill_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_skill_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_skill_active_version` FOREIGN KEY (`active_version_id`) REFERENCES `ai_skill_versions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
