CREATE TABLE `ai_skill_versions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `skill_id` bigint(20) unsigned NOT NULL,
  `parent_version_id` bigint(20) unsigned DEFAULT NULL,
  `version_number` int(10) unsigned NOT NULL,
  `source` enum('imported','manual','learned') NOT NULL,
  `status` enum('draft','active','rejected','archived') NOT NULL DEFAULT 'draft',
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_by_name` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(1024) NOT NULL DEFAULT '',
  `change_summary` text DEFAULT NULL,
  `package_sha256` char(64) NOT NULL,
  `validated_at` datetime(3) DEFAULT NULL,
  `activated_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_skill_version` (`skill_id`,`version_number`),
  UNIQUE KEY `uniq_skill_package` (`skill_id`,`package_sha256`),
  KEY `fk_version_parent` (`parent_version_id`),
  KEY `fk_version_created_by` (`created_by`),
  CONSTRAINT `fk_version_skill` FOREIGN KEY (`skill_id`) REFERENCES `ai_skills` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_version_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_version_parent` FOREIGN KEY (`parent_version_id`) REFERENCES `ai_skill_versions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
