CREATE TABLE `mcp_servers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `url` varchar(512) NOT NULL,
  `auth_type` enum('none','api_key','oauth') NOT NULL DEFAULT 'none',
  `api_key_enc` varbinary(2048) DEFAULT NULL,
  `oauth_client_id` varchar(255) DEFAULT NULL,
  `oauth_client_secret_enc` varbinary(2048) DEFAULT NULL,
  `oauth_access_token_enc` varbinary(4096) DEFAULT NULL,
  `oauth_refresh_token_enc` varbinary(4096) DEFAULT NULL,
  `oauth_token_expires_at` datetime(3) DEFAULT NULL,
  `oauth_metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`oauth_metadata`)),
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `tool_prefix` varchar(64) NOT NULL,
  `last_synced_at` datetime(3) DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ws_name` (`workspace_id`,`name`),
  UNIQUE KEY `uniq_ws_prefix` (`workspace_id`,`tool_prefix`),
  CONSTRAINT `fk_mcp_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
