CREATE TABLE `oauth_refresh_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `token_hash` char(64) NOT NULL,
  `client_pk` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `scopes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`scopes`)),
  `family_id` char(32) NOT NULL,
  `parent_id` bigint(20) unsigned DEFAULT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `revoked` tinyint(1) NOT NULL DEFAULT 0,
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_refresh_token_client` (`client_pk`),
  UNIQUE KEY `token_hash` (`token_hash`),
  KEY `idx_family` (`family_id`),
  KEY `idx_expires` (`expires_at`),
  KEY `fk_refresh_token_user` (`user_id`),
  KEY `fk_refresh_token_workspace` (`workspace_id`),
  CONSTRAINT `fk_refresh_token_client` FOREIGN KEY (`client_pk`) REFERENCES `oauth_clients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_refresh_token_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_refresh_token_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
