CREATE TABLE `tools` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint(20) unsigned NOT NULL,
  `name` varchar(191) NOT NULL,
  `kind` enum('builtin','custom','client','internal','mcp') NOT NULL,
  `template` varchar(64) DEFAULT NULL,
  `friendly_name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `input_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`input_schema`)),
  `risk` enum('read_only','internal_write','external_communication','financial_action','destructive_action','admin_action') NOT NULL,
  `requires_approval` tinyint(1) NOT NULL DEFAULT 0,
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`config`)),
  `guide` mediumtext DEFAULT NULL,
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `mcp_server_id` bigint(20) unsigned DEFAULT NULL,
  `remote_name` varchar(255) DEFAULT NULL,
  `definition_hash` char(64) DEFAULT NULL,
  `remote_missing` tinyint(1) NOT NULL DEFAULT 0,
  `definition_changed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ws_name` (`workspace_id`,`name`),
  KEY `idx_tool_mcp_server` (`mcp_server_id`),
  CONSTRAINT `fk_tool_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tool_mcp_server` FOREIGN KEY (`mcp_server_id`) REFERENCES `mcp_servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
