#!/usr/bin/env bash
#
# Regenerate scripts/seed-dev.sql from a database that scripts/seed-dev.py has
# already filled.
#
# The fixture is GENERATED, never hand-edited: a hand-maintained SQL file and
# the API that is supposed to have produced it drift apart within a week, and
# then the fixture describes a database the application can no longer make.
# Change the data in seed_content.py / seed-dev.py, re-seed, re-run this.
#
# What it deliberately leaves out:
#
#   ai_vendors.credentials_enc  The API keys, sealed with THIS machine's
#                               encryption key. Dumping them would put real
#                               vendor keys into the repository, and they would
#                               be undecryptable on any other machine anyway.
#                               Vendors come out with no credential; each
#                               machine adds its own.
#   tools, tool_grants          Tool rows are created from the code registry at
#                               boot. Shipping them would fight whatever the
#                               code says today.
#   user_sessions, oauth_*      Live credentials. Never.
#   agent_* runtime, jobs,      A transcript of somebody's conversation is not
#   model_calls, audit_logs     fixture data.
#   sag_db_version              The migration bookkeeping belongs to the
#                               database, not to the fixture.
#
# Usage: scripts/dump-seed-sql.sh [database] [user] [host]

set -euo pipefail

DB="${1:-flexie_sag}"
USER="${2:-sag}"
HOST="${3:-127.0.0.1}"
OUT="$(cd "$(dirname "$0")" && pwd)/seed-dev.sql"

# The password is not an argument: passing it on a command line puts it in
# every process listing on the machine.
: "${SAG_DB_PASSWORD:=sag}"
export MYSQL_PWD="$SAG_DB_PASSWORD"

# Order is dependency order, so the file reads sensibly even though it turns the
# checks off to load.
TABLES=(
  workspaces
  users
  workspace_members
  roles
  role_permissions
  user_groups_def
  group_roles
  user_group_members
  ai_models
  agents
  agent_allowed_tools
  agent_brains
  workflows
  workflow_versions
  workflow_assignments
  brains
  brain_categories
  brain_documents
  brain_document_links
  user_settings
)

# ai_vendors is emitted by hand below, with the secret left out.
WIPE=(ai_vendors "${TABLES[@]}")

{
  cat <<'HEADER'
-- Development seed data for Flexie SAG.
--
-- GENERATED by scripts/dump-seed-sql.sh from a database seeded through the REST
-- API (scripts/seed-dev.py). Do not edit by hand: change the seed and
-- regenerate, or the fixture stops describing anything the application can
-- actually produce.
--
-- Load it into a database that has been MIGRATED and is otherwise empty:
--
--     sag migrate up
--     mysql -u sag -p flexie_sag < scripts/seed-dev.sql
--
-- Sign in as any of these (all Administrators in workspace "acme"):
--
--     demo             / demo
--     admin@acme.test  / admin1234
--
-- The seeded people (elira.hoxha@acme.test and the rest) share the password
-- seed-Passw0rd! and are NOT administrators: they are there so that groups,
-- roles and workflow matching have something real to match on.
--
-- VENDOR KEYS ARE NOT IN HERE, on purpose. They are sealed with the encryption
-- key of the machine that seeded them, so they would be useless to you and
-- dangerous to us. The vendors and their models arrive with no credential:
-- open each vendor in the console and paste your own key.
HEADER

  echo
  echo "SET FOREIGN_KEY_CHECKS = 0;"
  echo
  echo "-- Empty what we are about to write, so this file can be loaded twice."
  for table in "${WIPE[@]}"; do
    echo "DELETE FROM \`${table}\`;"
  done
  echo

  echo "-- Vendors, with the sealed credential deliberately omitted."
  mysql --skip-column-names --batch -h "$HOST" -u "$USER" "$DB" <<'SQL'
SELECT CONCAT(
  'INSERT INTO `ai_vendors` (`id`,`workspace_id`,`vendor_key`,`name`,`base_url`,',
  '`credentials_enc`,`status`,`created_at`,`updated_at`) VALUES (',
  id, ',', workspace_id, ',', QUOTE(vendor_key), ',', QUOTE(name), ',',
  IFNULL(QUOTE(base_url), 'NULL'), ',NULL,', QUOTE(status), ',',
  QUOTE(created_at), ',', QUOTE(updated_at), ');')
FROM ai_vendors ORDER BY id;
SQL
  echo

  mysqldump -h "$HOST" -u "$USER" \
    --no-create-info --complete-insert --skip-extended-insert \
    --no-tablespaces --skip-add-locks --skip-disable-keys --skip-comments \
    --single-transaction --hex-blob --default-character-set=utf8mb4 \
    "$DB" "${TABLES[@]}"

  echo
  echo "SET FOREIGN_KEY_CHECKS = 1;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
